spring:
  application:
    name: spring-ai-tool-calling
  ai:
    openai:
      base-url: https://api-inference.modelscope.cn/
      #      base-url: http://localhost:8080
      api-key: b9f095df-2473-4165-871d-f65b59bdf127
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
logging:
  level:
    root: info
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
