server:
  port: 8010
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: spring-cloud-stream-quickstart
          binder: mybinder
      binders:
        mybinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.2.21
                port: 5672
                username: huey
                password: huey