spring:
  application:
    name: spring-ai-mcp-sse-server
  ai:
    openai:
      base-url: https://api-inference.modelscope.cn/
      api-key: b9f095df-2473-4165-871d-f65b59bdf127
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
    mcp:
      server:
        name: my-mcp-sse-server
        version: 1.0.0
        type: sync
        stdio: false
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message

