server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  application:
    name: spring-ai-quickstart
  ai:

    openai:
      base-url: https://api-inference.modelscope.cn/
      api-key:
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
