spring:
  ai:
    mcp:
      client:
        type: sync
        stdio:
          connections:
            filesystem:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "."
