spring:
  application:
    name: spring-ai-mcp-sse-client
  ai:
    openai:
      base-url: https://api-inference.modelscope.cn/
      api-key: b9f095df-2473-4165-871d-f65b59bdf127
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
    mcp:
      client:
        sse:
          connections:
            my-mcp-sse-server:
              url: http://localhost:8080
              sse-endpoint: /sse
