spring:
  application:
    name:
      spring-ai-advisors
  ai:
    openai:
      base-url: https://api-inference.modelscope.cn/
      api-key: f0e62da3-0d74-4688-b5ee-d511a6499a73
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
logging:
  level:
    root: info
    org.springframework.ai.chat.client.advisor: debug
